### ISSUE TITLE
Best practice for Multiparent population

### ISSUE THREAD

**Issue by jjdevega** [lvclark/polyRAD#33]
Hi,
THanks @lvclark for developing this package.

We have a multiparent heterozygous autotetraploid population with four families, one shared pollen donor and four mums, so offspring is half siblings. Our input in polyRAD is a filtered VCF with ok data. 

We are estimating genotype probabilities one family at the time following the tutorial. We use SubsetByTaxon and run one family at the time (quality control and PipelineMapping2Parents). Our PCAs per family look very similar to the example. We are exporting genotype probabilities for Mappoly and PolymapR, so we finish with four files x2 formats, one per family.
Offspring per family is uneven and we could benefit by "joining" the dataset somehow.

Questions:
=Is there a better way to work with these families than one at the time? 
=We have replicates for the parents, can we set donor/recurrent parent with several samples? 

THanks

**Comment by lvclark** [comment]
Good to hear from you Jose!  See this discussion regarding multiparent populations: https://github.com/lvclark/polyRAD/discussions/32#discussioncomment-4195617

For the parental replicates, I recommend a quick PCA to confirm that there are no mixups, then merge them with the `MergeTaxaDepth` function.
