### ISSUE TITLE
Error message on R when reading isoloci

### ISSUE THREAD

**Issue by deilepaita** [lvclark/polyRAD#36]
Hello Lindsay,

Thanks for the polyRAD package, it is well documented and the tutorials are awesome!

Following the steps for "Variant and Genotype Calling in Highly Duplicated Genomes" from https://lvclark.r-universe.dev/articles/polyRAD/isolocus_sorting.html, to call variants on my own dataset on a Miscanthus F2 diploid population, I get to the steps before importing the sorted dataset into polyRAD without any problems, but when trying to import the sorted .csv file generated by process_isoloci.py in R to polyRAD with the function readProcessIsoloci, I get the following error:
 
> myRAD <- readProcessIsoloci("20230315_out_sam_multi_1_sorted.csv", possiblePloidies = list(2), taxaPloidy = 2)
Reading file...
Filtering and sorting loci...
Building RADdata object...
Error in sum(sapply(seq_len(nsites), function(i) polyRADsubmat[splitnuc1[[a1]][i],  : 
  invalid 'type' (list) of argument

I don't quite understand the error message. Could you help me figure out what am I doing wrong? I tried changing default arguments, but still gives me the same error message no matter what I do.

Thanks,

**Comment by lvclark** [comment]
Hello,

In order to debug this, I'd need a small dataset that could be used to reproduce the error on my own machine.

**Comment by deilepaita** [comment]
Sure,

Here is a smaller set, only first ~1000 lines on the file "20230315_out_sam_multi_1_sorted.csv"

Copying the first ~1000 lines, just noticed that the file is not sorted by Marker name or location. Maybe that could be causing the problem?

[20230315_out_sam_multi_1_sorted_1000lines.csv](https://github.com/lvclark/polyRAD/files/11022864/20230315_out_sam_multi_1_sorted_1000lines.csv)

**Comment by deilepaita** [comment]
Loading the first 1000 lines works.

**Comment by lvclark** [comment]
Sorry for the delayed reply.  The blanks in the allele column could definitely cause this error.  I see in Chr01-003677744-bot that one of the tags is much shorter than the other two, and I bet the issue has something to do with that.  If you could send me the corresponding lines from the align.csv file that would be helpful.

**Comment by deilepaita** [comment]
Not a problem,

There are many cases like that one (Chr01-003677744-bot) in the sorted file. Attach you can find the corresponding lines to Chr01-003677744-bot in the align.csv file.

[20230315_out_sam_multi_1_align_Chr01-003677744-bot.csv](https://github.com/lvclark/polyRAD/files/11065426/20230315_out_sam_multi_1_align_Chr01-003677744-bot.csv)

Thanks for your help!

**Comment by lvclark** [comment]
Sorry again for the delayed response.  I just pushed a bug fix to process_isoloci.py that I think will solve your problem.  Let me know how it goes!

**Comment by deilepaita** [comment]
Thank you. I will let you know how it goes!

**Comment by deilepaita** [comment]
It work perfectly. I got no error this time.

Thanks for your help!
