### ISSUE TITLE
Export_MAPpoly error

### ISSUE THREAD

**Issue by kaurharpreet-umn** [lvclark/polyRAD#39]
Hello 

I am using polyRAD for calling genotypes in alfalfa crop. I have F1 progenies SNP data. I am having issues exporting the data out of polyRAD to run analysis in Mappoly. Here is the error I am getting:

`Error in object$posteriorProb[[ploidyIndex, as.character(pld.p)]] : 
   subscript out of bound` 

Thanks for your help!

Harpreet

**Comment by lvclark** [comment]
Hi Harpreet,

Would it be possible for you to share with me data and code that I can use to reproduce this error on my own machine?  It sounds like a bug in polyRAD but I can't solve it if I can't reproduce it.

Thanks,

Lindsay

**Comment by kaurharpreet-umn** [comment]
Thank you for your quick response, Lindsay!

Should I use this 'dragonzuela04@gmail.com' to share the files?

**Comment by lvclark** [comment]
Yes, that works!

**Comment by kaurharpreet-umn** [comment]
I have shared a link with you to access the files to replicate the error.

**Comment by lvclark** [comment]
I found the bug in `Export_MAPpoly` relating to how polyRAD 2.0 tracks ploidy within the object.  I will have that fixed and pushed to GitHub momentarily.  I also recommend running

``` r
mydata3$locTable$Chr <- sub("\\.1$", "", mydata3$locTable$Chr)
```

to avoid the warning about chromosome names.
