### ISSUE TITLE
HidHe is not found

### ISSUE THREAD

**Issue by Mghanbari43** [lvclark/polyRAD#7]
I am following tutorial for polyRad and noticed that function HindHe is not found when I wanna check skewness of markers based on  Mendelian ratio.  which library should be loaded?

**Comment by lvclark** [comment]
If you installed polyRAD from CRAN, it won't have HindHe yet.  Use `devtools::install_github("lvclark/polyRAD")` to get version 1.2.

Glad to see someone interested in this new feature!
